# Generated by Django 3.2.4 on 2021-06-14 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Isbn', models.IntegerField(primary_key=True, serialize=False, verbose_name='Isbn Del Libro')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Libro')),
                ('autor', models.CharField(max_length=50, verbose_name='Nombre del Libro')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Nombre del Libro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
